Update main_workflow.yml

diff --git a/.github/workflows/main_workflow.yml b/.github/workflows/main_workflow.yml
--- a/.github/workflows/main_workflow.yml
+++ b/.github/workflows/main_workflow.yml
@@ -12,9 +12,10 @@ on:
   #    - 'biopypir_matrix.md'
   #    -  'utils/package_params.json'
     
+    
   #  get linux distribution 
   # tabs add ID
-    
+  #  how to handle the repository dispatch running  many packages
 jobs:
   run_tests:
     runs-on: ${{ matrix.os }}
@@ -25,19 +26,19 @@ jobs:
     #env:       
     #  PACKAGE: scedar  
     steps:
-    - name: Create cache file
-      run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
+   # - name: Create cache file
+   #   run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
     #===============================================#
-    - name: Check SHA
-      id: check_sha
-      uses: actions/cache@v1
-      with:
-        path: check-SHA
-        key: check-SHA-${{ github.sha }}
+   # - name: Check SHA
+   #   id: check_sha
+   #   uses: actions/cache@v1
+   #   with:
+   #     path: check-SHA
+   #     key: check-SHA-${{ github.sha }}
     #===============================================#
-    - name: Some subsequent steps
-      if: steps.check_sha.outputs.cache-hit == 'true'
-      run: echo "Cache hit not found...Execute the subsequent steps"; exit 1 # no way to exit nicely?
+   # - name: Some subsequent steps
+   #   if: steps.check_sha.outputs.cache-hit == 'true'
+   #   run: echo "Cache hit not found...Execute the subsequent steps"; exit 1 # no way to exit nicely?
     #===============================================#
     - name: Dump GitHub context
       env:
@@ -48,7 +49,8 @@ jobs:
         RUNNER_CONTEXT: ${{ toJson(runner) }}
       run: echo "$RUNNER_CONTEXT"
     
-    - run: |
+    - name: set environment variables
+      run: |
         echo "${{ github.event.client_payload.PACKAGE }}"
         echo ${{ toJson(github.event.client_payload.PACKAGE) }}
         
