Update scedar_workflow.yml

diff --git a/.github/workflows/scedar_workflow.yml b/.github/workflows/scedar_workflow.yml
--- a/.github/workflows/scedar_workflow.yml
+++ b/.github/workflows/scedar_workflow.yml
@@ -14,23 +14,23 @@ jobs:
     env:       
       PACKAGE: scedar
       OWNER: TaylorResearchLab
-      tests_dir: "tests"
+      tests_dir: "tests/"
       ignore_tests: None
       ignore_lint: None
     steps:
-    - name: Create cache file
-      run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
+    #- name: Create cache file
+    #  run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
     #===============================================#
-    - name: Check SHA
-      id: check_sha
-      uses: actions/cache@v1
-      with:
-        path: check-SHA
-        key: check-SHA-${{ github.sha }}
+    #- name: Check SHA
+    #  id: check_sha
+    #  uses: actions/cache@v1
+    #  with:
+    #    path: check-SHA
+    #    key: check-SHA-${{ github.sha }}
     #===============================================#
-    - name: Some subsequent steps
-      if: steps.check_sha.outputs.cache-hit != 'true'
-      run: echo "Cache hit not found...Execute the subsequent steps" #; exit 1 # no way to exit nicely?
+    #- name: Some subsequent steps
+    #  if: steps.check_sha.outputs.cache-hit != 'true'
+    #  run: echo "Cache hit not found...Execute the subsequent steps" #; exit 1 # no way to exit nicely?
     #===============================================#
     - name: Dump GitHub context
       env:
