Update scedar_workflow.yml

diff --git a/.github/workflows/scedar_workflow.yml b/.github/workflows/scedar_workflow.yml
--- a/.github/workflows/scedar_workflow.yml
+++ b/.github/workflows/scedar_workflow.yml
@@ -16,6 +16,7 @@ jobs:
     env:       
       PACKAGE: scedar
       OWNER: TaylorResearchLab
+      pytest: True
       tests_dir: "tests/"
       ignore_tests: None
       ignore_lint: None
@@ -23,38 +24,16 @@ jobs:
     #- name: Create cache file
     #  run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
     #===============================================#
-    #- name: Check SHA
-    #  id: check_sha
-    #  uses: actions/cache@v1
-    #  with:
-    #    path: check-SHA
-    #    key: check-SHA-${{ github.sha }}
+    - name: Check SHA
+      id: check_sha
+      uses: actions/cache@v1
+      with:
+        path: check-SHA
+        key: check-SHA-${{ github.sha }}
     #===============================================#
-    #- name: Some subsequent steps
-    #  if: steps.check_sha.outputs.cache-hit != 'true'
-    #  run: echo "Cache hit not found...Execute the subsequent steps" #; exit 1 # no way to exit nicely?
-    #===============================================#
-    - name: Dump GitHub context
-      env:
-        GITHUB_CONTEXT: ${{ toJson(github) }}
-      run: |
-        echo "$GITHUB_CONTEXT" 
-    - name: Dump steps context
-      env:
-        STEPS_CONTEXT: ${{ toJson(steps) }}
-      run: echo "$STEPS_CONTEXT"
-    - name: Dump runner context
-      env:
-        RUNNER_CONTEXT: ${{ toJson(runner) }}
-      run: echo "$RUNNER_CONTEXT"
-    - name: Dump strategy context
-      env:
-        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
-      run: echo "$STRATEGY_CONTEXT"
-    - name: Dump matrix context
-      env:
-        MATRIX_CONTEXT: ${{ toJson(matrix) }}
-      run: echo "$MATRIX_CONTEXT"
+    - name: Some subsequent steps
+      if: steps.check_sha.outputs.cache-hit == 'true'
+      run: echo "Cache hit not found...Execute the subsequent steps"; exit 1 # no way to exit nicely?
     #===============================================#
     - name: checkout ${{env.PACKAGE}} repo 
       uses: actions/checkout@v2     
@@ -77,7 +56,7 @@ jobs:
       if: startsWith(matrix.os, 'ubuntu')
       uses: datreeio/validate-license-action@v1.0.0 
       with:
-        args: 'MIT,ISC,BSD'
+        args: "MIT,ISC,BSD"
     #===============================================#
     - name: INSTALL dependencies
       run: |
@@ -98,9 +77,9 @@ jobs:
       id: builder
       run: ./biopypir_utils.sh  "BUILD"
     #===============================================#
-    - name: PYTEST
-      id: local
-      run: ./biopypir_utils.sh "TEST"  
+    #- name: PYTEST
+    #  id: local
+    #  run: ./biopypir_utils.sh "TEST"  
     - name: pytest 2.0
       run: |
         pytest "tests"  \
