Update scedar_workflow.yml

diff --git a/.github/workflows/scedar_workflow.yml b/.github/workflows/scedar_workflow.yml
--- a/.github/workflows/scedar_workflow.yml
+++ b/.github/workflows/scedar_workflow.yml
@@ -138,12 +138,13 @@ jobs:
         #===============================================#
         - name: check for any job success, and cURL helper script
           run: |
-            ls -a
-            [ "$(ls -A parallel_runs)" ] && echo "Not Empty" || echo "No runs succeded, exiting...", exit 1;
-            echo "ALL JOBS FAILED"  > ${{github.run_number}}.json; mv ${{github.run_number}}.json logs/
-             
             curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/scedar_helper.sh"      
             chmod +x biopypir_utils.sh 
+        #    ls -a
+        #    [ "$(ls -A parallel_runs)" ] && echo "Not Empty" || echo "No runs succeded, exiting...", exit 1;
+        #    echo "ALL JOBS FAILED"  > ${{github.run_number}}.json; mv ${{github.run_number}}.json logs/
+             
+
         # replace w this: curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/${{ env.PACKAGE }}_helper.sh"      
         #===============================================#
         - name: EVALUATE jobs
