Update scedar_workflow.yml

diff --git a/.github/workflows/scedar_workflow.yml b/.github/workflows/scedar_workflow.yml
--- a/.github/workflows/scedar_workflow.yml
+++ b/.github/workflows/scedar_workflow.yml
@@ -136,18 +136,23 @@ jobs:
             path: parallel_runs/
         #===============================================#
         - name: check for any job success, and cURL helper script
+          if: success_check
           run: |
-             [ "$(ls -A /parallel_runs)" ] && echo "Not Empty" || echo "No runs succeded, exiting..."; exit 1;
-             echo "ALL JOBS FAILED"  > ${{github.run_number}}.json; mv ${{github.run_number}}.json logs/
+            ls -a
+            
+            [ "$(ls -A /parallel_runs/)" ] && echo "Not Empty" || echo "No runs succeded, exiting..."; exit 1;
+            echo "ALL JOBS FAILED"  > ${{github.run_number}}.json; mv ${{github.run_number}}.json logs/
              
-             curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/scedar_helper.sh"      
-             chmod +x biopypir_utils.sh 
+            curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/scedar_helper.sh"      
+            chmod +x biopypir_utils.sh 
         # replace w this: curl -L -o biopypir_utils.sh "https://raw.githubusercontent.com/benstear/biopypir_logs/master/.github/workflows/${{ env.PACKAGE }}_helper.sh"      
         #===============================================#
         - name: EVALUATE jobs
+          if: success()
           run: |
                 ./biopypir_utils.sh "EVAL" # no need for passing repo or run id, access through helpscript
                 ./biopypir_utils.sh "STATS"
+       #===============================================#
         - uses: geekyeggo/delete-artifact@v1
           with:
             name: |
